version: '3'

services:
    app:
        build: .
        restart: always
        ports: 
            - 3000:3000
        environment:
            MONGO_URI: mongodb://db/pastebin
            PORT: 3000
    db: 
        image: mongo
        restart: always
        volumes:
            - ./db/:/data/db